#!/usr/bin/env node
// Writes the Homebrew formula for a release from its SHA256SUMS (BUILD_PLAN §13). The release workflow
// commits the result to the 3ncryptor/homebrew-tap repository, so `brew install 3ncryptor/tap/kestrel`
// installs the prebuilt binary (no build from source, no dependencies).
//
//   node scripts/homebrew-formula.js <version> <SHA256SUMS> > Formula/kestrel.rb
const fs = require('node:fs');
const { parseSums } = require('../cli/release');

const REPO = 'https://github.com/3ncryptor/kestrel';
const BLOCKS = [
    ['on_macos', [['on_arm', 'darwin-arm64'], ['on_intel', 'darwin-x64']]],
    ['on_linux', [['on_arm', 'linux-arm64'], ['on_intel', 'linux-x64']]],
];

function formula({ version, sums }) {
    const digests = parseSums(sums);
    const archive = (target) => {
        const name = `kestrel-v${version}-${target}.tar.gz`;
        const sha = digests.get(name);
        if (!sha) throw new Error(`no checksum for ${name}`);
        return `      url "${REPO}/releases/download/v${version}/${name}"\n      sha256 "${sha}"`;
    };
    const platforms = BLOCKS.map(([os, arches]) => [
        `  ${os} do`,
        ...arches.map(([arch, target]) => `    ${arch} do\n${archive(target)}\n    end`),
        '  end',
    ].join('\n')).join('\n\n');
    return `# Generated by scripts/homebrew-formula.js for Kestrel v${version}. Do not edit by hand.
class Kestrel < Formula
  desc "System monitor and process manager for the terminal"
  homepage "${REPO}"
  version "${version}"
  license "MIT"

${platforms}

  def install
    bin.install "kestrel"
  end

  test do
    assert_match "kestrel #{version}", shell_output("#{bin}/kestrel --version")
    assert_match "\\"processCount\\"", shell_output("#{bin}/kestrel sm --dump --ticks 1")
  end
end
`;
}

if (require.main === module) {
    const [version, sumsFile] = process.argv.slice(2);
    if (!version || !sumsFile) {
        process.stderr.write('usage: node scripts/homebrew-formula.js <version> <SHA256SUMS>\n');
        process.exit(2);
    }
    try {
        process.stdout.write(formula({ version: version.replace(/^v/, ''), sums: fs.readFileSync(sumsFile, 'utf-8') }));
    } catch (err) {
        process.stderr.write(`homebrew-formula: ${err.message}\n`);
        process.exit(1);
    }
}

module.exports = { formula };
